gui:
  theme:
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - "#3a3a3a"
    selectedRangeBgColor:
      - "#3a3a3a"
    optionsTextColor:
      - white
